////////////////////////////////////////////////////////////////////////////////////////////////
// convert to int
int x = 3;
int x = 3.3;
int x = true;
int x = "323";
int x = "Omar";
// convert to float
float x = 3;
float x = 3.3;
float x = true;
float x = "323";
float x = "Omar";
// convert to bool
bool x = 3;
bool x = 0;
bool x = 3.3;
bool x = true;
bool x = "323";
bool x = "Omar";
// convert to string
string x = 3;
string x = 0;
string x = 3.3;
string x = true;
string x = "323";
string x = "Omar";